config/routes.rb
Bindery::Application.routes.draw do

  # mount the resque admin interface
  mount Resque::Server,:at => "/queues"

   get "bookmarks/clear", :to => "bookmarks#clear", :as => "clear_bookmarks"
  resources :bookmarks

  devise_for :users, class_name: "LoginCredential", controllers: {registrations:  "users/registrations"}
  as :user do
    get "signin", :to => "devise/sessions#new"
    post "signin", :to => "devise/sessions#create", class_name: "LoginCredential"
    get "signout", :to => "devise/sessions#destroy"
  end

  get 'users/registrations' => 'users/registrations#index', :as => 'login_credentials'

  # Drives is a redirect point for google oauth, so it can't have any dynamic segments
  resources :drives, :only=>[:index]
  
  resources :models, :except=>[:create, :index] do
    resources :fields, only:[:create]
    resources :associations, :only=>:create
    #resources :nodes 
  end


  resources :nodes, :only=>[] do
    resources :associations, :only=>[:index, :create]
  end


  resources :jobs
  resources :job_log_items
  resources :spreadsheet_rows
  root :to => 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
    end
  end
  
  
  resources :identities, :only=>[:index, :show]

  #jasmine is the path of our testing library so, we have restricted identities from begining with 'jasmine'
  constraints = {:id=>/(?!jasmine)[^\/\.]*/} unless Rails.env.production?
  resources :identities, :path=>'', :only=>[], :constraints=>constraints do
    resources :chattels
    get 'exhibits/:exhibit_id' => 'catalog#index', :as => 'exhibit'
    get 'exhibits/:exhibit_id/facet/:id' => 'catalog#facet', :as => :exhibit_facet

    resources :exhibits, :only=>[] do
      resources :solr_document, :path => '', :controller => 'catalog', :only => [:show, :update]
    end

    get ':pool_id/search' => 'pool_searches#index', :as => 'pool_search'
    get ':pool_id/overview' => 'pool_searches#overview', :as => 'pool_overview'
    

    resources :pools, :path=>'' do
      resources :fields, only:[:index,:show,:new]
      resources :exhibits, :except=>[:show]
      resources :audience_categories do
        resources :audiences
      end
      resources :file_entities do
        collection do
          get "s3_upload_info"
        end
      end
      get '/facet/:id' => 'pool_searches#facet', :as => :pool_search_facet

      # can't do :path => '' because that breaks models, nodes, etc. in client api
      resources :solr_document, :path => 'results', :controller => 'pool_searches', :only => [:show, :update]
      resources :drives, :only=>[:index] do
        collection do
          get 'spawn'
        end
      end
      resources :models do
        resources :nodes, :only=>[] do
          collection do
            get 'search'
          end
        end
      end
      resources :nodes, :only=>[:create, :update, :show, :new, :index, :destroy] do
        collection do
          get 'search'
          post 'find_or_create'
          post 'import'
        end
        match 'files' => 'nodes#attach_file', :via=>:post
      end
      resources :mapping_templates
      resources :spawn_jobs
      resources :spreadsheets do
        resources :worksheets do
        end
      end
      resources :chattels, :only=>[] do
        member do
          get 'describe'
        end
      end
    end
  end

end

app/models/concerns/bindery/node.rb
module Bindery::Node
  extend ActiveSupport::Concern

  included do
    include Bindery::Identifiable
    include Bindery::Node::DataManipulations
    include Bindery::Node::HasFiles
    include Bindery::Node::Finders
    include Bindery::Node::Indexing
    include Bindery::Node::Versioning
    include Bindery::Node::Forking
    include Bindery::Node::Importing
    include Bindery::Node::Associations
  end

  # If the type is "File Entity"
  def add_behaviors
    if model && model.file_entity?
      extend FileEntity
    end
  end

  def to_param
    # Do we need to_key also?
    persistent_id
  end


  # Overrides default assign_attributes behavior.
  # Resets modified_by every time the attributes change via this method
  #  -- if you don't provide modified_by or modified_by_id, it will be set to nil
  def assign_attributes(new_attributes)
    return unless new_attributes
    unless (new_attributes.has_key?(:modified_by) && !new_attributes[:modified_by].nil?) || (new_attributes.has_key?(:modified_by_id) && !new_attributes[:modified_by_id].nil?)
      self.modified_by = nil
    end
    super
  end

  # Overrides alias that points to ActiveRecord::AttributeAssignment.assign_attributes.  Point to local method instead.
  alias attributes= assign_attributes

  # copy-on-write
  # Mints a new node version with updated attributes, saves that new version and returns it
  def update
    n = Node.copy(self)
    #update_file_ids
    #n = Node.new
    #copied_values = self.attributes.select {|k, v| !['created_at', 'updated_at', 'id'].include?(k) }
    #copied_values[:parent_id] = id
    #n.assign_attributes(copied_values)
    n.save
    n
  end

  # override activerecord updates to use custom copy-on-write
  def update_record
    update
  end

  # reroute  activerecord updates to use custom copy-on-write
  #def create_or_update
  #  raise ReadOnlyRecord if readonly?
  #  #result = new_record? ? create_record : update_record
  #  if new_record?
  #    result = create_record
  #  else
  #    result = update
  #  end
  #  result != false
  #end

  def title
    @title ||= data[model.label_key].present? ? data[model.label_key] : persistent_id
  end

  def as_json(opts=nil)
    h = super
    h["pool"] = pool.short_name
    h["identity"] = pool.owner.short_name
    h["title"] = title
    h["node_version_id"] = id
    #h.merge!(h.delete("associations"))
    #h.merge!(h.delete("data"))
    h
  end

  # This ensures that persistent_id is used as the key when nodes and associations are serialized as a hash
  def serializable_hash(args)
    hash = super
    hash['id'] = hash['persistent_id']
    hash
  end


end

app/models/concerns/bindery/node/associations.rb
module Bindery::Node::Associations
  extend ActiveSupport::Concern

  def associations_for_json
    output = {}
    update_file_ids
    model.associations.each do |a|
      output[a.name] = []
      if associations[a.id.to_s] && associations[a.id.to_s].kind_of?(Array)
        associations[a.id.to_s].each do |id|
          node = Node.latest_version(id)
          output[a.name] <<  node.association_display if node
        end
      end
    end
    output['undefined'] = []
    if associations['undefined']
      associations['undefined'].each do |id|
        node = Node.latest_version(id)
        output['undefined'] << node.association_display if node
      end
    end
    if files
      output['files'] = []
      files.each do |file_entity|
        output['files'] << file_entity.association_display
      end
    end
    output
  end

  def association_display
    serializable_hash(:only=>[:id, :persistent_id], :methods=>[:title])
  end

end

app/models/concerns/bindery/node/importing.rb
module Bindery::Node::Importing
  extend ActiveSupport::Concern

  module ClassMethods
    def bulk_import_records(records, pool, model)
      nodes = records.map do |record|
        node = Node.new(pool:pool, model:model, data:record)
        node.generate_uuid
        node
      end
      self.import_nodes(nodes)
    end

    def import_nodes(nodes)
      result = self.import(nodes)
      Bindery.index( nodes.map {|n| n.to_solr} )
      Bindery.solr.commit
      result
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  include Blacklight::Controller
  include Blacklight::SolrHelper
  load_and_authorize_resource :except=>[:index, :search, :update, :create, :import, :find_or_create], :find_by => :persistent_id
  load_and_authorize_resource :pool, :find_by => :short_name, :through=>:identity
  load_resource :model, through: :node, singleton: true, only: [:show]

  def index
    if params[:model_id]
      @model = Model.find(params[:model_id])
      authorize! :read, @model
      @nodes = @model.nodes.where("nodes.pool_id = ?", @pool)
    else
      @nodes = @pool.nodes
    end
    respond_to do |format|
      format.html do
        @models = @pool.models
      end
      format.json do
        render json: 
          @nodes.to_json(:only=>[:id, :persistent_id, :data, :associations, :model_id])
      end
    end
  end

  def search
    if params[:model_id]
      @model = Model.find(params[:model_id])
      authorize! :read, @model
    end

    # Constrain results to this pool
    fq = "pool:#{@pool.id}"
    fq += " AND model:#{@model.id}" if @model
    fq += " AND format:Node"

    ## TODO do we need to add query_fields for File entities?
    query_fields = @pool.models.map {|model| model.field_codes.map{ |key| Node.solr_name(key) } }.flatten.uniq
    (solr_response, @facet_fields) = get_search_results( params, {:qf=>(query_fields + ["pool"]).join(' '), :qt=>'search', :fq=>fq, :rows=>1000, 'facet.field' => ['name_si', 'model']})
    
    # puts "# of solr_docs: #{solr_response.docs.length}"
    # puts "solr_response: #{solr_response.docs}"
    @results = solr_response.docs.map{|d| Node.find_by_persistent_id(d['id'])}
    

    respond_to do |format|
      format.json do
        render json: @results
      end
    end
  end

  def new
    @models = @pool.models
    ## IF params[:binding] is passed, they are binding a file.
    ## ELSE IF params[:model_id] is passed, they are creating a new entity.
    if params[:binding] 
      @node.binding = params[:binding]
      render :new_binding
      return
    end
    @node.model = Model.find(params[:model_id])
    authorize! :read, @node.model
  end

  def show
    respond_to do |format|
      format.mp3 do
        if @node.model == Model.file_entity
          send_data @node.content, :type=>@node.mime_type, :disposition => 'inline'
        else
          render :file => "public/404", :status => :not_found, :layout=>nil
        end
      end
      format.ogg do
        if @node.model == Model.file_entity
          require 'open3'
          ## by default rails sets the encoding to UTF_8, this causes a UndefinedConversionError
          ## when dealing with binary data.
          Encoding.default_internal = nil
          ## run mpg321 reading from stdin, in quiet mode, encoding to wav
          ## take that stream and encode it with oggenc in quiet mode 
          ## read the output (stdout) and stream it to the web client
          stdin, stdout, wait_thr = Open3.popen2('mpg321 - -q -w -|oggenc - -Q')
          stdin.write @node.content
          stdin.close
          send_data stdout.read, :type=>'ogg', :disposition => 'inline'
          stdout.close
          Encoding.default_internal = Encoding::UTF_8 #Restore default expected by rails
        else
          render :file => "public/404", :status => :not_found, :layout=>nil
        end
      end
      format.json { render json: serialize_node(@node) }
      format.html 
    end
  end
  
  def create
    authorize! :create, Node
    @node = Node.new(node_params)
    @node.modified_by = @identity
    begin
      model = @pool.models.find(params[:node][:model_id])
    rescue ActiveRecord::RecordNotFound 
      #User didn't have access to the model they were trying to set.
      redirect_to new_identity_pool_node_path(@identity, @pool, :binding=>@node.binding)
      return
    end
    @node.model = model
    @node.pool = @pool
    @node.save!
    respond_to do |format|
      format.html { redirect_to identity_pool_search_path(@identity, @pool), :notice=>"#{model.name} created" }
      format.json { render :json=>serialize_node(@node)}
    end
  end

  def import
    authorize! :create, Node
    model = @pool.models.find(params[:model_id])
    @import_results = Node.bulk_import_records(params[:data], @pool, model)
    respond_to do |format|
      format.html { redirect_to identity_pool_search_path(@identity, @pool), :notice=>"#{params[:data].count} #{model.name.pluralize} created" }
      format.json { render :json=>@import_results}
    end
  end
  
  # Uses advanced search request handler to find Nodes matching the request.
  # Currently only searches against attribute values.  Does not search against associations (though associations in the create request will be applied to the Node if created.)
  def find_or_create
    authorize! :create, Node
    init_node_from_params
    
    # Find...
    # Constrain results to this pool
    fq = "pool:#{@pool.id}"
    fq += " AND model:#{@model.id}" if @model
    fq += " AND format:Node"
    
    query_parts = []
    @node.solr_attributes.each_pair do |key, value|
      query_parts << "#{key}:\"#{value}\""
    end
    query = query_parts.join(" && ")
    # puts query

    ## TODO do we need to add query_fields for File entities?
    query_fields = @pool.models.map {|model| model.fields.map{ |field| Node.solr_name(field) } }.flatten.uniq
    (solr_response, @facet_fields) = get_search_results( {:q=>query}, {:qf=>(query_fields + ["pool"]).join(' '), :qt=>'advanced', :fq=>fq, :rows=>10, 'facet.field' => ['name_si', 'model']})
    
    #puts "solr_response: #{solr_response.docs}"
    
    # If any docs were found, load the first result as a node and return that.  
    # Otherwise, create a new one based on the params provided.
    first_result = solr_response.docs.first
    if first_result.nil?
      @node.save
      flash[:notice] = "Created a new #{@node.model.name} based on your request."
    else
      @node =  Node.find_by_persistent_id(first_result['id'])
      flash[:notice] = "Found a #{@node.model.name} matching your query."
    end
    
    respond_to do |format|
      format.html { render file: "nodes/show"}
      format.json { render :json=>serialize_node(@node)}
    end
  end

  def update
    @node = Node.find_by_persistent_id(params[:id])
    authorize! :update, @node
    @node.attributes = node_params
    @node.modified_by = @identity
    new_version = @node.update
    respond_to do |format|
      format.html { redirect_to identity_pool_solr_document_path(@identity, @pool, new_version), :notice=>"#{@node.model.name} updated" }
      format.json { head :no_content }
    end
  end
  
  def destroy
    node_name = @node.title
    @pool = @node.pool
    @node.destroy
    flash[:notice] = "Deleted \"#{node_name}\"."
    redirect_to identity_pool_search_path(identity_id: current_identity, pool_id: @pool)
  end

  def attach_file
    @node = Node.find_by_persistent_id(params[:node_id])
    authorize! :attach_file, @node
    if @pool.default_file_store.nil?
      respond_to do |format|
        error = "You must set up a file store before attaching a file"
        format.html { redirect_to identity_pool_node_path(@identity, @pool, @node), :alert=>error   }
        format.json { render :json=>{:status=>:error, :errors=>[error]}, :status=>:unprocessable_entity}
      end
      return
    end


    new_version = @node.attach_file(params[:file_name], params[:file])
    respond_to do |format|
      format.html { redirect_to identity_pool_node_path(@identity, @pool, new_version), :notice=>"Attached file" }
      format.json { head :no_content }
    end

  end

  private

  # Whitelisted attributes for create/update
  def node_params
    if params.has_key?(:node)
      node_params = params.require(:node)
    else
      node_params = params
    end
    node_params.permit(:binding).tap do |whitelisted|
      if node_params[:data]
        whitelisted[:data] = node_params[:data]
      end
      if node_params[:associations]
        whitelisted[:associations] = node_params[:associations]
      end
    end
  end

  def serialize_node(n)
    hash = n.as_json.merge({url: identity_pool_node_path(n.pool.owner, n.pool, n), pool: n.pool.short_name, identity: n.pool.owner.short_name, binding: n.binding, model_id: n.model_id })
    ["id", "parent_id", "pool_id", "identity_id", "created_at", "updated_at"].each {|key| hash.delete(key)}
    return hash
  end

  def blacklight_solr
    @solr ||=  RSolr.connect(blacklight_solr_config)
  end

  def blacklight_solr_config
    Blacklight.solr_config
  end
  
  def init_node_from_params
    begin
      model = @pool.models.find(params[:node][:model_id])
    rescue ActiveRecord::RecordNotFound 
      #User didn't have access to the model they were trying to set.
      redirect_to new_identity_pool_node_path(@identity, @pool, :binding=>@node.binding)
      return
    end
    @node = Node.new(node_params)
    @node.model = model
    @node.pool = @pool
  end

end
  

app/helpers/nodes_helper.rb
module NodesHelper
  def draw_field(field, default=nil)
    case field["type"]
    when "text" 
      draw_text_field(field, default)
    when "date"
      draw_date_field(field, default)
    else
      draw_text_field(field, default)
    end
  end
  
  def link_to_node(node)
    link_to node.title, identity_pool_solr_document_path(@identity, @pool, node)
  end
  
  private

  def draw_text_field(field, default)
    content_tag(:div, :class=> 'control-group') do
      label_tag("node[data][#{field["code"]}]", field["name"]) + 
      text_field_tag("node[data][#{field["code"]}]", default)
    end
  end
  
  def draw_date_field(field, default)
    content_tag(:div, :class=> 'control-group') do
      label_tag("node[data][#{field["code"]}]", field["name"]) + 
      content_tag(:input, "", {:name=>"node[data][#{field["code"]}]", :type=>"date", :class=> 'control-group'})
    end
  end
end

app/views/nodes/_association.html.erb
<tr class="association">
  <td>
    <a href="#" data-bind="text: title, attr:{href: '<%= identity_pool_path(@identity, @pool)%>/nodes/'+persistent_id}"></a>
  </td>
  <td>
    <a href="#" class="remove" data-bind="click: function(data, event) { $root.removeAssociation($parent.code, data, event) }">x</a>
  </td>
</tr>

app/views/nodes/_association_set.html.erb
<div class="association ui-droppable" data-bind="foreach: model.associations, visible: model.associations.length > 0">
  <h4 data-bind="text: name"></h4>
  <a href="#" data-bind="click: $root.openAssociationSearchPane">Add more</a>
  <table class="table table-bordered table-striped" data-bind="foreach: $parent.associations[code]">
    <%= render partial: "nodes/association"%>
  </table>
</div>
<%- if @node.model.allows_file_bindings? && @node.model != Model.file_entity %>
  <%= render partial: "nodes/files_list"%>
<%- end %>

app/views/nodes/_file.html.haml
%tr.association
  %td
    - if file.video?
      %i.icon-film
      = link_to file.file_name, identity_pool_node_path(@identity, @pool, file.persistent_id)
    - elsif file.audio?
      %i.icon-music
      = link_to file.file_name, identity_pool_node_path(@identity, @pool, file.persistent_id)
      %audio{src: file.s3_url.to_s, type: file.mime_type,  controls: "controls", preload: "metadata" }
        Your browser does not support the audio tag.
    - elsif file.image?
      %i.icon-picture
      = link_to file.file_name, identity_pool_node_path(@identity, @pool, file.persistent_id)
    - else 
      %i.icon-file
      = link_to file.file_name, identity_pool_node_path(@identity, @pool, file.persistent_id)
    .actions
      = link_to "download", file.s3_url.to_s, {class: "download"}

app/views/nodes/_files_list.html.haml
.association.ui-droppable
  %div{class:"association ui-droppable", "data-bind"=>"with: model.filesAssociation"}
    %h4 Files
    %ul
      %li
        %a{href:"#", "data-bind"=>"click: $root.openAssociationSearchPane"} Associate existing files
      %li=link_to "Upload new files", new_identity_pool_file_entity_path(@identity, @pool, target_node_id:@node.persistent_id)

    %table.table.table-bordered.table-striped
      = render partial: "nodes/file", collection: @node.files

app/views/nodes/_inbound_associations.html.erb
<div class="showView panel">
  <div class="panel-header">
    <h4>Things that reference this <%= @node.model.name %></h4>
  </div>
  <div class="panel-body">
    <table class="results table table-bordered table-striped">
      <%= render partial: "nodes/inbound_association", collection: @node.incoming %>
    </table>
  </div>
  <div class="panel-footer">
  </div>
</div>

app/views/nodes/_node.html.erb
<!-- ko with: currentEntity -->
<div class="showView panel panel-default">
  <div class="panel-header">
    <span class="modelName" data-bind="text: model.name, attr: {class: model.id}"></span>
    <h3 data-bind="text: title"></h3>
  </div>
  <div class="panel-body">
    <%- if @node.model == Model.file_entity %>
      <%= render partial:"file_entities/viewer", locals: {file:@node} %>
    <%- end %>
    <%= form_for @node, url: identity_pool_node_path(@identity.short_name, @pool.short_name, @node),"accept-charset" => "UTF-8", html: {class: "metadata"}  do |f| %>
      <%= render partial: "nodes/field" %>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary" data-bind="click: $root.updateEntity">Save</button> <span id="lastSavedAt" data-bind="text: lastSavedAt"></span>
      </div>
    <% end %>
    </form>
    <div class="associations">
      <%= render partial: "nodes/association_set" %>
    </div>
  </div>
  <div class="panel-footer">
    <nav>
      <a href="#" data-bind="attr:{href: pool_url+'/models#'+model.id+'/edit'}">Change Structure</a>
      <%= button_to("Delete this #{@model.name}", {:action => :destroy, :controller => :nodes, :id => @node.persistent_id, pool_id: @pool, identity_id: @identity}, :confirm => "Are you sure you want to delete the \"#{@node.title}\" #{@model.name} and all of its associations?", :method => :delete ) %>
    </nav>
  </div>
</div>
<!-- /ko -->
<%= render file: "nodes/search" %>
<%= render partial: "nodes/inbound_associations" %>
<%= render file: "nodes/node_explorer", :formats => [:js]%>

app/views/nodes/_node_read_only.html.haml
%dl.dl-horizontal.dl-invert
  - node.data.each_pair do |field_code, values|
    - field_spec = node.model.fields.select {|f| f["code"] == field_code}.first
    %dt= field_spec["name"]
    %dd= values

app/views/nodes/_search_form.html.erb
<form class="form-search">
  <div class="input-append">
    <input id="query" type="text" class="input-medium search-query" data-bind="value: query, click: $root.runEntitySearch">
    <button type="submit" class="btn" data-bind="click: $root.runEntitySearch">Search</button>
  </div>
</form>

app/views/nodes/new.html.erb
<div class="panel-header">
  <a href="#" class="close">×</a>
  <h3>New Entity</h3>
</div>

<div class="panel-body">
  <form accept-charset="UTF-8" class="metadata">
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </form>
</div>

app/views/nodes/new_binding.html.haml
%h1 Description

=form_for @node do |f|
  %h2 File Info
  %dl
    %dt File Name
    %dd Look this up from google? #{@node.binding}
  =f.hidden_field :binding

  %h2 Bindings/Associations
  .control-group
    =f.label :model_id, "This file is a(n) example of "
    .controls
      =f.select :model_id, options_from_collection_for_select(@models, :id, :name)

  .form-actions
    =f.submit "Associate", :class=>'btn btn-primary'

app/views/nodes/show.html.erb
<div id="document" class="<%= render_document_class %>">
  <div id="doc_<%= @node.persistent_id.to_s.parameterize %>">

    <%#= render_document_heading.html_safe %>
    <div class="tools"><%#= render :partial => 'pool_searches/show_tools' %></div>
    <div class="document">
      <%= render partial: "nodes/node" %>
    </div>
  </div>
</div>

app/views/nodes/showAssociation.html.erb
<div class="association ui-droppable" data-bind="foreach: model.associations, visible: model.associations.length > 0">
  <h4 data-bind="text: label"></h4>
  <table class="table table-bordered table-striped" data-bind="with: $parent.associations[name]">
    <tr><td class="association"><a href="#" data-bind="text: $data, click: $root.loadAndOpenEntity"></a></td></tr>
  </table>
</div>

app/views/nodes/showField.html.erb
<div class="controlGroup" data-bind="foreach: model.fields">
  <label data-bind="text: name, attr: {for: code}"></label>
  <input data-bind="value: $parent.data[$data.code], attr: {type: type, name: code}">
</div>