config/routes.rb
Bindery::Application.routes.draw do

  # mount the resque admin interface
  mount Resque::Server,:at => "/queues"

   get "bookmarks/clear", :to => "bookmarks#clear", :as => "clear_bookmarks"
  resources :bookmarks

  devise_for :users, class_name: "LoginCredential", controllers: {registrations:  "users/registrations"}
  as :user do
    get "signin", :to => "devise/sessions#new"
    post "signin", :to => "devise/sessions#create", class_name: "LoginCredential"
    get "signout", :to => "devise/sessions#destroy"
  end

  get 'users/registrations' => 'users/registrations#index', :as => 'login_credentials'

  # Drives is a redirect point for google oauth, so it can't have any dynamic segments
  resources :drives, :only=>[:index]
  
  resources :models, :except=>[:create, :index] do
    resources :fields, only:[:create]
    resources :associations, :only=>:create
    #resources :nodes 
  end


  resources :nodes, :only=>[] do
    resources :associations, :only=>[:index, :create]
  end


  resources :jobs
  resources :job_log_items
  resources :spreadsheet_rows
  root :to => 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
    end
  end
  
  
  resources :identities, :only=>[:index, :show]

  #jasmine is the path of our testing library so, we have restricted identities from begining with 'jasmine'
  constraints = {:id=>/(?!jasmine)[^\/\.]*/} unless Rails.env.production?
  resources :identities, :path=>'', :only=>[], :constraints=>constraints do
    resources :chattels
    get 'exhibits/:exhibit_id' => 'catalog#index', :as => 'exhibit'
    get 'exhibits/:exhibit_id/facet/:id' => 'catalog#facet', :as => :exhibit_facet

    resources :exhibits, :only=>[] do
      resources :solr_document, :path => '', :controller => 'catalog', :only => [:show, :update]
    end

    get ':pool_id/search' => 'pool_searches#index', :as => 'pool_search'
    get ':pool_id/overview' => 'pool_searches#overview', :as => 'pool_overview'
    

    resources :pools, :path=>'' do
      resources :fields, only:[:index,:show,:new]
      resources :exhibits, :except=>[:show]
      resources :audience_categories do
        resources :audiences
      end
      resources :file_entities do
        collection do
          get "s3_upload_info"
        end
      end
      get '/facet/:id' => 'pool_searches#facet', :as => :pool_search_facet

      # can't do :path => '' because that breaks models, nodes, etc. in client api
      resources :solr_document, :path => 'results', :controller => 'pool_searches', :only => [:show, :update]
      resources :drives, :only=>[:index] do
        collection do
          get 'spawn'
        end
      end
      resources :models do
        resources :nodes, :only=>[] do
          collection do
            get 'search'
          end
        end
      end
      resources :nodes, :only=>[:create, :update, :show, :new, :index, :destroy] do
        collection do
          get 'search'
          post 'find_or_create'
          post 'import'
        end
        match 'files' => 'nodes#attach_file', :via=>:post
      end
      resources :mapping_templates
      resources :spawn_jobs
      resources :spreadsheets do
        resources :worksheets do
        end
      end
      resources :chattels, :only=>[] do
        member do
          get 'describe'
        end
      end
    end
  end

end

app/controllers/pool_searches_controller.rb
class PoolSearchesController < ApplicationController
  load_and_authorize_resource :identity, :find_by => :short_name
  load_and_authorize_resource :pool, :find_by => :short_name, :through=>:identity
  load_and_authorize_resource instance_name: :node, class: Node, find_by: :persistent_id, only: [:show]
  load_resource :model, through: :node, singleton: true, only: [:show]
  
  before_filter :set_perspective
  before_filter :load_configuration
  before_filter :load_model_for_grid
  before_filter :convert_facet_fields_params
  before_filter :convert_sort_fields_params

  include Blacklight::Controller
  def layout_name
    'application'
  end
  include Blacklight::Catalog
  include Bindery::AppliesPerspectives
  include GoogleRefineSupport

  solr_search_params_logic << :add_pool_to_fq << :add_index_fields_to_qf << :ensure_model_filtered_for_grid << :apply_audience_filters

      # get search results from the solr index
  # Had to override the whole method (rather than using super) in order to add json support
  def index

    extra_head_content << view_context.auto_discovery_link_tag(:rss, url_for(params.merge(:format => 'rss')), :title => t('blacklight.search.rss_feed') )
    extra_head_content << view_context.auto_discovery_link_tag(:atom, url_for(params.merge(:format => 'atom')), :title => t('blacklight.search.atom_feed') )


    if params["queries"]
      do_refine_style_query
    else
      (@response, @document_list) = get_search_results
    end

    @filters = params[:f] || []

    respond_to do |format|
      format.html { save_current_search_params }
      format.rss  { render :layout => false }
      format.atom { render :layout => false }
      format.json do
        @marshalled_results ||= marshall_nodes(@document_list.map{|d| d["id"]})
        if params["nodesOnly"] || params["queries"]
          render  json: @marshalled_results
        else
          render json: json_response
        end
      end
    end
  end

  # Provides a pool overview with models, perspectives and facets
  def overview
    authorize! :show, @pool
    (@response, @document_list) = get_search_results(rows:0)
    respond_to do |format|
      format.json { render :json=>{id:@pool.id, models:@pool.models.as_json, perspectives:@pool.exhibits.as_json, facets:@response["facet_counts"]["facet_fields"], numFound:@response["response"]["numFound"] } }    
    end
  end
  
  
  protected

  # Given an Array of persistent_ids, loads the corresponding Nodes
  # @document_list [Array] Array of persistent_ids of Nodes that should be loaded
  def marshall_nodes(node_id_list)
    node_id_list.map{|nid| Node.find_by_persistent_id(nid)}
  end

  def json_response
    json_response = @response
    #json_response["docs"] = @response["response"]["docs"].map {|solr_doc| serialize_work_from_solr(solr_doc) }
    json_response["docs"] = @marshalled_results
    json_response
  end

  def load_configuration
    @blacklight_config = Blacklight::Configuration.new
    @blacklight_config.configure do |config|
      ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
      config.default_solr_params = { 
        :qt => 'search',
        :fl => '*', 
        :rows => 10 
      }

      ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
      ## parameters included in the Blacklight-jetty document requestHandler.
      #
      #config.default_document_solr_params = {
      #  :qt => 'document',
      #  ## These are hard-coded in the blacklight 'document' requestHandler
      #  # :fl => '*',
      #  # :rows => 1
      #  # :q => '{!raw f=id v=$id}' 
      #}

      # solr field configuration for search results/index views
      config.index.show_link = 'title'
      config.index.record_display_type = 'model_name'

      # solr field configuration for document/show views
      config.show.html_title = 'title'
      config.show.heading = 'title'
      config.show.display_type = 'model_name'

      # solr fields that will be treated as facets by the blacklight application
      #   The ordering of the field names is the order of the display
      #
      # Setting a limit will trigger Blacklight's 'more' facet values link.
      # * If left unset, then all facet values returned by solr will be displayed.
      # * If set to an integer, then "f.somefield.facet.limit" will be added to
      # solr request, with actual solr request being +1 your configured limit --
      # you configure the number of items you actually want _displayed_ in a page.    
      # * If set to 'true', then no additional parameters will be sent to solr,
      # but any 'sniffed' request limit parameters will be used for paging, with
      # paging at requested limit -1. Can sniff from facet.limit or 
      # f.specific_field.facet.limit solr request params. This 'true' config
      # can be used if you set limits in :default_solr_params, or as defaults
      # on the solr side in the request handler itself. Request handler defaults
      # sniffing requires solr requests to be made with "echoParams=all", for
      # app code to actually have it echo'd back to see it.  
      #
      # :show may be set to false if you don't want the facet to be drawn in the 
      # facet bar
      exhibit.facets.uniq.each do |field|
        unless blacklight_config.facet_fields.keys.include?( Node.solr_name(field) )
          if field.kind_of?(Field)
            if field.name.nil?
              field.name = field.code.humanize
            end
            config.add_facet_field Node.solr_name(field), :label => field.name.humanize, limit: 10
          else
            case field
              when "model_name"
                config.add_facet_field Node.solr_name(field, type: 'facet'), :label => "Model", limit: 10
              when String
                config.add_facet_field Node.solr_name(field, type: 'facet'), :label => field.humanize, limit: 10
            end
          end
        end
      end

      # Have BL send all facet field names to Solr, which has been the default
      # previously. Simply remove these lines if you'd rather use Solr request
      # handler defaults, or have no facets.
      config.add_facet_fields_to_solr_request!

      # solr fields to be displayed in the index (search results) view
      #   The ordering of the field names is the order of the display 
      exhibit.index_fields.uniq.each do |field|
        #if f == "model_name"
        #  config.add_index_field Node.solr_name(f, type: 'facet'), :label => "Model"
        #else
        #  config.add_index_field Node.solr_name(f), :label => f.humanize+':'
        #end
        unless blacklight_config.index_fields.keys.include?( Node.solr_name(field) )
          if field.kind_of?(Field)
            if field.name.nil?
              field.name = field.code.humanize
            end
            config.add_index_field Node.solr_name(field), :label => field.name+':'
          else
            case field
              when "model_name"
                config.add_index_field Node.solr_name(field, type: 'facet'), :label => "Model"
              when String
                config.add_index_field Node.solr_name(field), :label => field.humanize+':'
            end
          end
        end
      end
      # query_fields = exhibit.pool.models.map {|model| model.keys.map{ |key| Node.solr_name(key) } }.flatten.uniq
      #solr_parameters[:qf] = query_fields + ["pool"]

      # solr fields to be displayed in the show (single result) view
      #   The ordering of the field names is the order of the display 
      exhibit.index_fields.uniq.each do |field|
        unless blacklight_config.show_fields.keys.include?( Node.solr_name(field) )
          if field.kind_of?(Field)
            if field.name.nil?
              field.name = field.code.humanize
            end
            config.add_show_field Node.solr_name(field), :label => field.name+':'
          else
            case field
              when "model_name"
                config.add_show_field Node.solr_name(field, type: 'facet'), :label => "Model"
              when String
                config.add_show_field Node.solr_name(field), :label => field.humanize+':'
            end
          end
        end
      end

      # "fielded" search configuration. Used by pulldown among other places.
      # For supported keys in hash, see rdoc for Blacklight::SearchFields
      #
      # Search fields will inherit the :qt solr request handler from
      # config[:default_solr_parameters], OR can specify a different one
      # with a :qt key/value. Below examples inherit, except for subject
      # that specifies the same :qt as default for our own internal
      # testing purposes.
      #
      # The :key is what will be used to identify this BL search field internally,
      # as well as in URLs -- so changing it after deployment may break bookmarked
      # urls.  A display label will be automatically calculated from the :key,
      # or can be specified manually to be different. 

      # This one uses all the defaults set by the solr request handler. Which
      # solr request handler? The one set in config[:default_solr_parameters][:qt],
      # since we aren't specifying it otherwise. 
      
      config.add_search_field 'all_fields', :label => 'All Fields'
      
      # "sort results by" select (pulldown)
      # label in pulldown is followed by the name of the SOLR field to sort by and
      # whether the sort is ascending or descending (it must be asc or desc
      # except in the relevancy case).
      config.add_sort_field 'score desc, title asc', :label => 'relevance'
      config.add_sort_field 'timestamp desc, title asc', :label => 'recently modified'
      config.add_sort_field 'title asc', :label => 'title'

      
      # If there are more than this many search results, no spelling ("did you 

app/views/pool_searches/_constraints.html.erb
<div id="appliedParams">

	<h3 class="label"><%= t('blacklight.search.filters.title') %></h3>
  
  <%= render_constraints(localized_params) %>  
		
</div>

app/views/pool_searches/_document_list.html.erb
<% # container for all documents in index view -%>
<div id="documents">
  <%= render documents, :as => :document %>
</div>

app/views/pool_searches/_facet_limit.html.erb
<ul>
  <% paginator =    
      Blacklight::Solr::FacetPaginator.new(display_facet.items,        
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <li>
    <% if facet_in_params?( solr_field, item.value ) %>              
        <%= render_selected_facet_value(solr_field, item) %>              
      <% else %>              
        <%= render_facet_value(solr_field, item) %>              
    <% end -%>
    </li>
  <% end %>

  <% if(paginator.has_next?)  %>
    <li class="more_facets_link"><%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %></li>
  <% end %>

</ul>

app/views/pool_searches/_model_chooser.html.haml
.navbar.navbar-fixed-bottom
  .navbar-inner
    %ul.nav#select-view
      %li.nav-header View:
      %li{class: ("active" if params["view"] != "grid")}
        =link_to "browse", url_for(params_for_search.merge(view: "browse"))
      %li{class: ("active" if params["view"] == "grid")}
        =link_to "grid", url_for(params_for_search.merge(view: "grid"))
    %ul.nav#model-chooser
      %li.nav-header Model:
      - selected_model_id = @model_for_grid.nil? ? "all" : @model_for_grid.id
      - if params["view"] != "grid"
        %li{class: ("active" if selected_model_id == "all")}
          =link_to "All Models", url_for(params_for_search.except(:model_id))
      - @pool.models.each do |m|
        - if selected_model_id == m.id
          %li{class:"active", "data-model-id"=>m.id, "data-model-json"=>m.as_json}
            =link_to m.name, url_for(params_for_search.merge(model_id: m.id))
        - else
          %li{"data-model-id"=>m.id}
            =link_to m.name, url_for(params_for_search.merge(model_id: m.id))

app/views/pool_searches/_paginate_compact.html.erb
<% if paginate_params(@response).num_pages > 1 %>
<%= paginate_rsolr_response @response, :theme => :blacklight_compact %>
<% else %>
<%= render_pagination_info(@response) %>
<% end %>

app/views/pool_searches/_perspective_chooser.html.haml
%ul.perspectives.css-dropdown
  %li.btn
    = @exhibit.title
    %ul
      - @pool.perspectives.select{|p| p != @exhibit}.each do |p|
        %li
          =link_to p.title, identity_pool_search_path(@identity.short_name, @pool.short_name, perspective:(p.id ? p.id : 0))

app/views/pool_searches/_search_form_grid.html.haml
= form_tag search_action_url, :method => :get, :class => 'search-query-form span9' do
  = search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe

  -#- unless search_fields.empty?
  -#  .perspective-chooser.pull-left
  -#    %label#search_field.hide-text= t('bindery.perspectives.switch')
  -#    = render partial: "pool_searches/perspective_chooser"
  .input-append.pull-left
    %label.hide-text{for:"q"}= t('blacklight.search.form.q')
    = text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q", :id => "q"
    %button#search.btn.btn-primary.search-btn{type:"submit"}
      %span.submit-search-text=t('blacklight.search.form.submit')
      %i.icon-search.icon-white"

app/views/pool_searches/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark/Folder functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.
-%>
  <ul class="tools">
  
    <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
      <li class="cite">
      <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :name => 'citation', :class => 'lightboxLink'} %>
      </li>
    <% end %>
    
    <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
      <li class="refworks">
      <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document) %>        
      </li>
    <% end %>
    
    <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <%= link_to t('blacklight.tools.email'), email_catalog_path(:id => @document), {:id => 'emailLink', :name => 'email', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    <%- if @document.respond_to?( :to_sms_text ) -%>
      <li class="sms">
      <%= link_to t('blacklight.tools.sms'), sms_catalog_path(:id => @document), {:id => 'smsLink', :name => 'sms', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :name => 'librarian_view', :class => 'lightboxLink'} %>
      </li>
    <% end %>
    
  </ul>

app/views/pool_searches/_sort_and_per_page.html.erb
<div id="sortAndPerPage">
   <div class="page_links">
     <%= render :partial => "paginate_compact" %>
   </div>

    <%= render partial: "view_type_chooser" %>
    <%= render :partial => 'sort_widget' %>

    <%= render :partial => 'per_page_widget' %>



</div>

app/views/pool_searches/_sort_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.sort_fields.blank? %>
<div id="sort-dropdown" class="dropdown pull-right hidden-phone">
  <ul class="css-dropdown">
    <li class="btn">
      <%= link_to(t('blacklight.search.sort.label', :field =>current_sort_field.label), "#") %> <span class="caret"></span>
      <ul>
        <%- blacklight_config.sort_fields.each do |sort_key, field| %>
          <li><%= link_to(field.label, url_for(params_for_search.merge(:sort => sort_key))) %></li>
        <%- end -%>
      </ul>
    </li>
  </ul>
</div>
<% end %>

app/views/pool_searches/facet.html.erb
<% sidebar_items << capture do %>
  <p><%= link_back_to_catalog %></p>
<% end %>

<div class="facet_pagination top">
  <%= render :partial=>'catalog/facet_pagination' %>
</div>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3><%= facet_field_labels[params[:id]] %></h3>
</div>
<div class="modal-body">
  <div class="facet_extended_list">

    <ul class="facet_extended_list">
      <% @pagination.items.each do |item| %>
        <li>
          <% if facet_in_params?( params[:id], item.value ) %>              
            <%= render_selected_facet_value(params[:id], item) %>              
          <% else %>              
            <%= render_facet_value(params[:id], item) %>              
          <% end -%>
        </li>
      <% end %>
    </ul>
  </div>
</div>
  
<div class="modal-footer">

  <div class="facet_pagination bottom">
    <%= render :partial=>'catalog/facet_pagination' %>
  </div>
</div>

app/views/pool_searches/index.html.erb
<%- unless params["view"] == "foo" %>
  <div id="sidebar" class="span3">
    <%= render :partial=>'perspective_chooser' %>    
   <%= render :partial=>'catalog/facets' %>
  </div><!--/well -->
<%- end %>

  <div id="content" class="span9">   

      <h1><%=@pool.name%></h1>
      <% extra_head_content << render_opensearch_response_metadata.html_safe %>

      <%- unless params["view"] == "grid" %>

        <div class="row"><%=render :partial=>'search_form'%></div>
        <% @page_title = t('blacklight.search.title', :application_name => application_name) %>

        <%= render :partial => 'catalog/did_you_mean' %>

        <%= render :partial => 'catalog/constraints' %>

        <%= render 'pool_searches/sort_and_per_page' %>
      <%- end %>

      <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>

      <%- if params[:view] == "grid" %>
        <%= render :partial => 'pool_searches/grid/document_grid', locals: {documents: @document_list} %>
      <%- else %>
        <%= render :partial => 'document_list', locals: {documents: @document_list} %>
      <%- end %>


      <%= render 'catalog/results_pagination' %>
  </div>

app/views/pool_searches/index.html.haml
- if params["view"] == "grid"
  = render file:"pool_searches/index_grid"
- else
  = render file:"pool_searches/index_browse"
= render partial:"pool_searches/model_chooser"