config/routes.rb
Bindery::Application.routes.draw do

  # mount the resque admin interface
  mount Resque::Server,:at => "/queues"

   get "bookmarks/clear", :to => "bookmarks#clear", :as => "clear_bookmarks"
  resources :bookmarks

  devise_for :users, class_name: "LoginCredential", controllers: {registrations:  "users/registrations"}
  as :user do
    get "signin", :to => "devise/sessions#new"
    post "signin", :to => "devise/sessions#create", class_name: "LoginCredential"
    get "signout", :to => "devise/sessions#destroy"
  end

  get 'users/registrations' => 'users/registrations#index', :as => 'login_credentials'

  # Drives is a redirect point for google oauth, so it can't have any dynamic segments
  resources :drives, :only=>[:index]
  
  resources :models, :except=>[:create, :index] do
    resources :fields, only:[:create]
    resources :associations, :only=>:create
    #resources :nodes 
  end


  resources :nodes, :only=>[] do
    resources :associations, :only=>[:index, :create]
  end


  resources :jobs
  resources :job_log_items
  resources :spreadsheet_rows
  root :to => 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
    end
  end
  
  
  resources :identities, :only=>[:index, :show]

  #jasmine is the path of our testing library so, we have restricted identities from begining with 'jasmine'
  constraints = {:id=>/(?!jasmine)[^\/\.]*/} unless Rails.env.production?
  resources :identities, :path=>'', :only=>[], :constraints=>constraints do
    resources :chattels
    get 'exhibits/:exhibit_id' => 'catalog#index', :as => 'exhibit'
    get 'exhibits/:exhibit_id/facet/:id' => 'catalog#facet', :as => :exhibit_facet

    resources :exhibits, :only=>[] do
      resources :solr_document, :path => '', :controller => 'catalog', :only => [:show, :update]
    end

    get ':pool_id/search' => 'pool_searches#index', :as => 'pool_search'
    get ':pool_id/overview' => 'pool_searches#overview', :as => 'pool_overview'
    

    resources :pools, :path=>'' do
      resources :fields, only:[:index,:show,:new]
      resources :exhibits, :except=>[:show]
      resources :audience_categories do
        resources :audiences
      end
      resources :file_entities do
        collection do
          get "s3_upload_info"
        end
      end
      get '/facet/:id' => 'pool_searches#facet', :as => :pool_search_facet

      # can't do :path => '' because that breaks models, nodes, etc. in client api
      resources :solr_document, :path => 'results', :controller => 'pool_searches', :only => [:show, :update]
      resources :drives, :only=>[:index] do
        collection do
          get 'spawn'
        end
      end
      resources :models do
        resources :nodes, :only=>[] do
          collection do
            get 'search'
          end
        end
      end
      resources :nodes, :only=>[:create, :update, :show, :new, :index, :destroy] do
        collection do
          get 'search'
          post 'find_or_create'
          post 'import'
        end
        match 'files' => 'nodes#attach_file', :via=>:post
      end
      resources :mapping_templates
      resources :spawn_jobs
      resources :spreadsheets do
        resources :worksheets do
        end
      end
      resources :chattels, :only=>[] do
        member do
          get 'describe'
        end
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'margins'

  def index
    if user_signed_in?
      @pools = Pool.for_identity(current_identity)
      render 'dashboard'
    else
      render 'index'
    end
  end
end

app/views/welcome/dashboard.html.haml
.row{style: "margin-top: 20px"}
  .span8
    .hero-unit
      %h1 Data Bindery
      %h2 What do your data look like?
      %p
        DataBindery allows you to turn everyday data into searchable pools of linked entities.
      %p
        To get started, create a pool and start putting data into it.  Some
        %a{href:"https://github.com/cocupu/databindery-client/wiki/DataBindery-Help"} reference info for users
        is accumulating on the project wiki.
      %p 
        %b Disclaimer
        This is the most minimal, barely viable, pre-Beta version of DataBindery.  It's ugly, slow and incomplete, but it's a start!  I'm working on it in my spare time while paying the bills by doing freelance work on 
        %a{href: "http://projecthydra.org"} Hydra-based
        digital repository solutions through
        %a{href: "http://curationexperts.com"} Data Curation Experts
        \.  At this moment, I 
        %i cannot provide any guarantees of uptime, security or protection from data loss.
        Think of this as an extremely early experimental run.
      %p 
        If you want to see more features (or ongoing support), email me about pre-paying for a subscription or hire my team through 
        %a{href: "http://curationexperts.com"} Data Curation Experts 
        and pay us to make the product amazing.
      %p 
        %b 
          %a{href:"https://vimeo.com/68724818"} Check out the walkthrough 
        of what you can currently do with DataBindery.  
      = render partial: "walkthrough_video"
      %p 
        %b If you have questions, ideas, suggestions, 
        or anything else to chime in about, sign up to the 
        %a{href:"https://groups.google.com/forum/#!forum/databindery-users"} databindery Google Group and say hello.
      
        
  .span4
    &nbsp;
    %h3
      Your Pools
      %span.pool-count="(#{@pools.to_a.size})" #rails 6865 workaround
      =link_to "New Pool", new_identity_pool_path(controller.current_identity.short_name), :class=>'btn btn-new-pool'
    %ul.pools
      -@pools.each do |pool|
        %li
          %h2=link_to(pool.name, identity_pool_path(pool.owner.short_name, pool))
          %div.body
            %p.description=pool.description

app/views/welcome/index.html.haml
=content_for :page_name do
  What do your data look like?

.row
  .span7
    %p
      %b DataBindery
      allows you to turn everyday data into searchable pools of linked entities.

    %p Our goal is to enable an ecosystem of data usage and to encourage data-driven discourse in the pursuit of knowledge, innovation and happiness.  This platform gives you the shortest path between Collecting and Publishing data while providing the necessary tools for curating, controlling access and tracking usage.
    
    %p 
      %b Disclaimer
      This is the most minimal, barely viable, pre-Beta version of DataBindery.  It's ugly, slow and incomplete, but it's a start!  I'm working on it in my spare time while paying the bills by doing freelance work on 
      %a{href: "http://projecthydra.org"} Hydra-based
      digital repository solutions through
      %a{href: "http://curationexperts.com"} Data Curation Experts
      \.  At this moment, I 
      %i cannot provide any guarantees of uptime, security or protection from data loss.
      Think of this as an extremely early experimental run.
    %p 
      If you want to see more features (or ongoing support), email me about pre-paying for a subscription or Hire my team through 
      %a{href: "http://curationexperts.com"} Data Curation Experts 
      and pay us to make the product amazing.
    %p 
      %b 
        %a{href:"https://vimeo.com/68724818"} Check out the walkthrough 
      of what you can currently do with DataBindery.
    = render partial: "walkthrough_video"
    %p 
      %b If you have questions, ideas, suggestions, 
      or anything else to chime in about, sign up to the 
      %a{href:"https://groups.google.com/forum/#!forum/databindery-users"} databindery Google Group and say hello.
    
    %p DataBindery frees data from spreadsheets and Document-centric systems like Sharepoint by allowing you to collect arbitrary files into a pool, spawn structured data files (spreadsheets, xml, etc.) into a web of linked data, build connections between all the contents, and publish access-controlled exhibits with data-centric search interfaces and webservice APIs. 
        
  .span3.offset1

    %h3 Get started today!
    =form_for LoginCredential.new(identities_attributes:[{short_name:""}]), :as=>:user, :url=>user_registration_path  do |f|
      = f.fields_for :identities do |ident_form| 
        = ident_form.text_field :short_name, :placeholder=>"Username", :class=>'large' 
        .help-block Username may only contain alphanumeric characters or dashes and cannot begin with a dash.
      %br
      = f.email_field :email, :placeholder=>"E-Mail", :class=>'', :autocomplete=>'off' 
      %br
      = f.password_field :password, :placeholder=>"Password", :class=>'' 
      %br
      %br
      %button.btn.large.btn-primary{:type=>"submit"} Sign Up
      

%section
  .page-header
    %h1 See what our customers are doing with Data Bindery:



  %ul.col4
    %li
      =link_to '#' do
        =image_tag 'http://lorempixel.com/210/150/?1=true', :class=>'thumbnail', :width=>210, :height=>150
      %strong Lorem ipsum
    %li
      =link_to '#' do
        =image_tag 'http://lorempixel.com/210/150/?2=true', :class=>'thumbnail', :width=>210, :height=>150
      %strong Lorem ipsum
    %li
      =link_to '#' do
        =image_tag 'http://lorempixel.com/210/150/?3=true', :class=>'thumbnail', :width=>210, :height=>150
      %strong Lorem ipsum
    %li
      =link_to '#' do
        =image_tag 'http://lorempixel.com/210/150/?4=true', :class=>'thumbnail', :width=>210, :height=>150
      %strong Lorem ipsum