config/routes.rb
Bindery::Application.routes.draw do

  # mount the resque admin interface
  mount Resque::Server,:at => "/queues"

   get "bookmarks/clear", :to => "bookmarks#clear", :as => "clear_bookmarks"
  resources :bookmarks

  devise_for :users, class_name: "LoginCredential", controllers: {registrations:  "users/registrations"}
  as :user do
    get "signin", :to => "devise/sessions#new"
    post "signin", :to => "devise/sessions#create", class_name: "LoginCredential"
    get "signout", :to => "devise/sessions#destroy"
  end

  get 'users/registrations' => 'users/registrations#index', :as => 'login_credentials'

  # Drives is a redirect point for google oauth, so it can't have any dynamic segments
  resources :drives, :only=>[:index]
  
  resources :models, :except=>[:create, :index] do
    resources :fields, only:[:create]
    resources :associations, :only=>:create
    #resources :nodes 
  end


  resources :nodes, :only=>[] do
    resources :associations, :only=>[:index, :create]
  end


  resources :jobs
  resources :job_log_items
  resources :spreadsheet_rows
  root :to => 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
    end
  end
  
  
  resources :identities, :only=>[:index, :show]

  #jasmine is the path of our testing library so, we have restricted identities from begining with 'jasmine'
  constraints = {:id=>/(?!jasmine)[^\/\.]*/} unless Rails.env.production?
  resources :identities, :path=>'', :only=>[], :constraints=>constraints do
    resources :chattels
    get 'exhibits/:exhibit_id' => 'catalog#index', :as => 'exhibit'
    get 'exhibits/:exhibit_id/facet/:id' => 'catalog#facet', :as => :exhibit_facet

    resources :exhibits, :only=>[] do
      resources :solr_document, :path => '', :controller => 'catalog', :only => [:show, :update]
    end

    get ':pool_id/search' => 'pool_searches#index', :as => 'pool_search'
    get ':pool_id/overview' => 'pool_searches#overview', :as => 'pool_overview'
    

    resources :pools, :path=>'' do
      resources :fields, only:[:index,:show,:new]
      resources :exhibits, :except=>[:show]
      resources :audience_categories do
        resources :audiences
      end
      resources :file_entities do
        collection do
          get "s3_upload_info"
        end
      end
      get '/facet/:id' => 'pool_searches#facet', :as => :pool_search_facet

      # can't do :path => '' because that breaks models, nodes, etc. in client api
      resources :solr_document, :path => 'results', :controller => 'pool_searches', :only => [:show, :update]
      resources :drives, :only=>[:index] do
        collection do
          get 'spawn'
        end
      end
      resources :models do
        resources :nodes, :only=>[] do
          collection do
            get 'search'
          end
        end
      end
      resources :nodes, :only=>[:create, :update, :show, :new, :index, :destroy] do
        collection do
          get 'search'
          post 'find_or_create'
          post 'import'
        end
        match 'files' => 'nodes#attach_file', :via=>:post
      end
      resources :mapping_templates
      resources :spawn_jobs
      resources :spreadsheets do
        resources :worksheets do
        end
      end
      resources :chattels, :only=>[] do
        member do
          get 'describe'
        end
      end
    end
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  load_and_authorize_resource :identity, :find_by => :short_name
  load_and_authorize_resource :exhibit
  load_and_authorize_resource instance_name: :node, class: Node, find_by: :persistent_id, only: [:show]

  before_filter :load_configuration

  include Blacklight::Controller
  def layout_name
    'application'
  end
  include Blacklight::Catalog
  include Bindery::AppliesPerspectives

  solr_search_params_logic << :add_pool_to_fq << :add_index_fields_to_qf << :process_sort_field_params

  protected

  def load_configuration
    @blacklight_config = Blacklight::Configuration.new
    @blacklight_config.configure do |config|
      ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
      config.default_solr_params = { 
        :qt => 'search',
        :fl => '*', 
        :rows => 10 
      }

      ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
      ## parameters included in the Blacklight-jetty document requestHandler.
      #
      #config.default_document_solr_params = {
      #  :qt => 'document',
      #  ## These are hard-coded in the blacklight 'document' requestHandler
      #  # :fl => '*',
      #  # :rows => 1
      #  # :q => '{!raw f=id v=$id}' 
      #}

      # solr field configuration for search results/index views
      config.index.show_link = 'title'
      config.index.record_display_type = 'model_name'

      # solr field configuration for document/show views
      config.show.html_title = 'title'
      config.show.heading = 'title'
      config.show.display_type = 'model_name'

      # solr fields that will be treated as facets by the blacklight application
      #   The ordering of the field names is the order of the display
      #
      # Setting a limit will trigger Blacklight's 'more' facet values link.
      # * If left unset, then all facet values returned by solr will be displayed.
      # * If set to an integer, then "f.somefield.facet.limit" will be added to
      # solr request, with actual solr request being +1 your configured limit --
      # you configure the number of items you actually want _displayed_ in a page.    
      # * If set to 'true', then no additional parameters will be sent to solr,
      # but any 'sniffed' request limit parameters will be used for paging, with
      # paging at requested limit -1. Can sniff from facet.limit or 
      # f.specific_field.facet.limit solr request params. This 'true' config
      # can be used if you set limits in :default_solr_params, or as defaults
      # on the solr side in the request handler itself. Request handler defaults
      # sniffing requires solr requests to be made with "echoParams=all", for
      # app code to actually have it echo'd back to see it.  
      #
      # :show may be set to false if you don't want the facet to be drawn in the 
      # facet bar
      @exhibit.facets.uniq.each do |key|
        if key == "model_name"
          config.add_facet_field Node.solr_name(key, type: 'facet'), :label => "Model", limit: 10
        else
          config.add_facet_field Node.solr_name(key, type: 'facet'), :label => key.humanize, limit: 10
        end
      end


      # Have BL send all facet field names to Solr, which has been the default
      # previously. Simply remove these lines if you'd rather use Solr request
      # handler defaults, or have no facets.
      config.add_facet_fields_to_solr_request!

      # solr fields to be displayed in the index (search results) view
      #   The ordering of the field names is the order of the display 
      @exhibit.index_fields.uniq.each do |f|
        if f == "model_name"
          config.add_index_field Node.solr_name(f, type: 'facet'), :label => "Model"
        else
          config.add_index_field Node.solr_name(f), :label => f.humanize+':' 
        end
      end
      # query_fields = @exhibit.pool.models.map {|model| model.keys.map{ |key| Node.solr_name(key) } }.flatten.uniq
      #solr_parameters[:qf] = query_fields + ["pool"]

      # solr fields to be displayed in the show (single result) view
      #   The ordering of the field names is the order of the display 
      @exhibit.index_fields.uniq.each do |f|
        if f == "model_name"
          config.add_show_field Node.solr_name(f, type: 'facet'), :label => "Model"
        else
          config.add_show_field Node.solr_name(f), :label => f.humanize+':' 
        end
      end

      # "fielded" search configuration. Used by pulldown among other places.
      # For supported keys in hash, see rdoc for Blacklight::SearchFields
      #
      # Search fields will inherit the :qt solr request handler from
      # config[:default_solr_parameters], OR can specify a different one
      # with a :qt key/value. Below examples inherit, except for subject
      # that specifies the same :qt as default for our own internal
      # testing purposes.
      #
      # The :key is what will be used to identify this BL search field internally,
      # as well as in URLs -- so changing it after deployment may break bookmarked
      # urls.  A display label will be automatically calculated from the :key,
      # or can be specified manually to be different. 

      # This one uses all the defaults set by the solr request handler. Which
      # solr request handler? The one set in config[:default_solr_parameters][:qt],
      # since we aren't specifying it otherwise. 
      
      config.add_search_field 'all_fields', :label => 'All Fields'
      
      # "sort results by" select (pulldown)
      # label in pulldown is followed by the name of the SOLR field to sort by and
      # whether the sort is ascending or descending (it must be asc or desc
      # except in the relevancy case).
      config.add_sort_field 'score desc, title asc', :label => 'relevance'
      config.add_sort_field 'timestamp desc, title asc', :label => 'recently modified'
      config.add_sort_field 'title asc', :label => 'title'

      # If there are more than this many search results, no spelling ("did you 
      # mean") suggestion is offered.
      config.spell_max = 5
    end
  end

  def add_pool_to_fq(solr_parameters, user_parameters)
    solr_parameters[:fq] ||= []
    solr_parameters[:fq] << "pool:#{@exhibit.pool_id}"

  end

  # The fields set in qf are the ones that we query on. A pretty good default is to use the fields we display.
  def add_index_fields_to_qf(solr_parameters, user_parameters)
    solr_parameters[:qf] ||= []
    solr_parameters[:qf] << 'title'
    blacklight_config.index_fields.each do |field_name, obj|
      solr_parameters[:qf] << field_name
    end
  end

  def process_sort_field_params(solr_parameters, user_parameters)
    if user_parameters.has_key?(:sort_fields)
      sorts = []
      #if solr_parameters[:sort]
      #  sorts << solr_parameters[:sort]
      #end
      user_parameters[:sort_fields].each do |sort_options|
        field = Field.find(sort_options[:field_id])
        sorts << "#{field.solr_name} #{sort_options[:direction]}"
      end
      solr_parameters[:sort] = sorts.join(",")
    end

  end

end

app/views/catalog/_document_header.html.erb
     
      <% # header bar for doc items in index view -%>
      <div class="documentHeader">
        
        <% # bookmark functions for items/docs -%>
        <%= render_index_doc_actions document, :wrapping_class => "documentFunctions hidden-phone" %>
        
        <% # main title container for doc partial view -%>
          <h5 class="index_title">
          <%= t('blacklight.search.documents.counter', :counter => (document_counter + 1 + @response.params[:start].to_i)) %><%= link_to render_document_index_label(document, :label=>blacklight_config.index.show_link.to_sym), identity_exhibit_solr_document_path(@identity, @exhibit, document), 'data-counter' => (document_counter + 1 + @response.params[:start].to_i) %></h5>
      </div>
      

app/views/catalog/_show_default.html.haml
- # default partial to display solr document fields in catalog show view
%dl.dl-horizontal.dl-invert
  - document_show_fields.each do |solr_fname, field|
    - if should_render_show_field? document, field
      %dt{class: "blacklight-#{solr_fname.parameterize}"}= render_document_show_field_label :field => solr_fname
      %dd{class: "blacklight-#{solr_fname.parameterize}"}= render_document_show_field_value :document => document, :field => solr_fname

= render partial: "file_entities/file_list_read_only"

#associations
  - @node.associations.each_pair do |association_type, association_pids|
    - association_spec = @node.model.associations.select {|a| a["code"] == association_type}.first
    - if association_pids && association_spec
      %h2= association_spec["name"]
      - associated_nodes = @node.reify_association(association_type).nil? ? [] : @node.reify_association(association_type)
      - associated_nodes.each do |associated_node|
        %div= render partial: "nodes/node_read_only", locals: {node: associated_node}

app/views/catalog/index.html.erb
  <div id="sidebar" class="span3">
   <%= render :partial=>'facets' %>
  </div><!--/well -->

<div id="content" class="span9">   

    <h1><%=@exhibit.title%></h1>
    <div class="row"><%=render :partial=>'search_form'%></div>
    <% @page_title = t('blacklight.search.title', :application_name => application_name) %>


    <% extra_head_content << render_opensearch_response_metadata.html_safe %>

    <%= render :partial => 'did_you_mean' %>

    <%= render :partial => 'constraints' %>

    <%= render 'sort_and_per_page' %> 

    <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>
    <%#= @document_list.inspect %>
    <%= render :partial => 'document_list', locals: {documents: @document_list} %>


    <%= render 'results_pagination' %>
</div>